### ISSUE TITLE
Bug: NY!Azura refined weapon wrong stats

### ISSUE THREAD

**Issue by titanix** [feh-stuff/feh-stuff.github.io#5]
Hello,

I was working on my NY!Azura and I found a behavior which is likely a bug in applicating the value of the refined values of Hagoita+.

Equipped with Hagoita, no problem for the stat for the +res/-res. There is the expected 37/44/32/22/29 stats.
[In-game stats](https://unixorn.azurewebsites.net/feh/feh_hagoita.png)
[Builder stats](https://unixorn.azurewebsites.net/feh/builder_hagoita.png)

However when trying to apply the refined bonus (+5 HP, +3 SPD), there is only +2 HP and +2 SPD added in the builder. The 39/44/34/22/29 does not match the expected 42/44/35/22/29.
[In-game stats](https://unixorn.azurewebsites.net/feh/feh_hagoita_plus.png)
[Builder stats](https://unixorn.azurewebsites.net/feh/builder_hagoita_plus.png)

Problems exists for the other refinements as well, not in the same intensity (+4 for RES is OK but not the HP, +3 instead of +4 DEF and missing HP, +1 ATK instead of +2, missing HP).

Regards.

**Comment by feh-stuff** [comment]
It was caused by a duplicate Hagoita+ data which for some reason had Hama Ya+ refine's stats. I've fixed it.

Thanks.
