### ISSUE TITLE
Bug: L'Arachel - Ivaldi does not add +3 defense

### ISSUE THREAD

**Issue by solendale** [feh-stuff/feh-stuff.github.io#7]
There's actually a few more of these that I noticed while tinkering around with other characters. I'll try to maybe do a master bug for it if that's more convenient.

**Comment by feh-stuff** [comment]
Thanks for finding these bugs. I've fixed the weapon stats for Ivaldi, Gleipnir, Great Flame, Thani, and Flame Siegmund.
